name: rupee_isar_codegen
description: Isolated Isar code generation (avoids flutter_riverpod analyzer conflict).
publish_to: none

environment:
  sdk: ^3.12.0

dependencies:
  isar: ^3.1.0+1

dev_dependencies:
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
